version: '2'
services:
  web:
    image: vulhub/drupal:8.5.0
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal

